### ISSUE TITLE
Needless CastShadow on parts

### ISSUE THREAD

**Issue by x5tb** [Ukendio/Game#13]
Some of the parts on the map I've created have castshadow needlessly on, The map has 2800 parts and every part that CastShadow isn't required on should be turned off to improve performance.

**Comment by x5tb** [comment]
![image](https://user-images.githubusercontent.com/56361008/119724669-a0c87280-be34-11eb-9387-8e7f3673cb87.png)

**Comment by Ukendio** [comment]
Thanks, I have now adjusted settings
