### ISSUE TITLE
Weapon skins

### ISSUE THREAD

**Issue by x5tb** [Ukendio/Game#14]
Right now there is one gun and thats it, I think weapon skins would give the game more of a visual variety to already current weapons. Maybe keep players in the game longer? Such as skins as a reward for doing something ingame, Like kills, play time, or anything else. After all whats better then grinding for hours to get a skin for your favourite weapon? I think skins would be a good addition to the game in the future for these reasons.

**Comment by Ukendio** [comment]
I agree! There should be more skins, we need to figure out standard texture conventions. This needs to be after we have gotten all standard weapons done first though.
