### ISSUE TITLE
Customizable Weapon Parts

### ISSUE THREAD

**Issue by D0RYU** [Ukendio/Game#18]
hey what if we could unlock weapon parts like a scope or let’s say a knife attachment in game

ik phantom forces has this but I think we can make it unique by doing it differently

example what if you unlock parts by completing challenges instead of buying them
maybe you can unlock parts in secret parts of the game

also if this is added I feel like we should have unique attachments for each weapon so they are not always the same

what do you guys think?

**Comment by Ukendio** [comment]
This adds a lot of complexity, does these part change things cosmetically or functionally? 

I was thinking more along the lines of Arsenal, a simple casual game anyone can make where guns are static models. But I think your idea is certainly intriguing.

**Comment by D0RYU** [comment]
> This adds a lot of complexity, does these part change things cosmetically or functionally?
> 
> I was thinking more along the lines of Arsenal, a simple casual game anyone can make where guns are static models. But I think your idea is certainly intriguing.

it would change functionally or cosmetically it would depend

if we went functionally some things could be like less recoil
if we went cosmetically some things could be like scopes which could improve aim

we don't need to add this, if you want to do arsenal style this isn't needed as it would be unfair for new players in that style of game
