### ISSUE TITLE
Map has no barriers

### ISSUE THREAD

**Issue by x5tb** [Ukendio/Game#28]
The map has simple walls as barriers, But these can easily be crossed over.
![image](https://user-images.githubusercontent.com/56361008/120032850-6ab7f980-bfc0-11eb-9d20-765e58b979d8.png)
Example:
Almost anyone can just go over these obstacles to get over the walls.
![image](https://user-images.githubusercontent.com/56361008/120032977-989d3e00-bfc0-11eb-9d22-48bafbf905c5.png)
There is another one here.
![image](https://user-images.githubusercontent.com/56361008/120033186-e023ca00-bfc0-11eb-99b8-c15e17328d7a.png)
I could go on and on finding locations where this is possible. If someone were to cross over the walls there is no way back and they would be stuck there. The problem is that there should be something there to stop them, either making the obstacles shorter or farther, or the easier solution, creating map barriers by placing invisible walls right above the visible walls, that way if someone were to try and jump over the wall, they would hit the invisible brick and fall straight to the ground.

**Comment by Ukendio** [comment]
I have now added invisible barriers
